openapi: 3.0.3
info:
  description: OpenAPI のファイルをサンプルとして作成
  title: OpenAPI のベース
  version: 1.0.0
servers:
- description: URL 一覧
  url: "{server}"
  variables:
    server:
      default: http://localhost:3000
tags:
- name: basic
paths:
  /product/{id}:
    get:
      description: 製品を 1 件返す
      operationId: getProductById
      parameters:
      - description: product id
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              example:
                id: 1
                name: 製品 A
                is_limited: false
                released_at: 2021/09/01
              schema:
                $ref: '#/components/schemas/product'
          description: 成功時
      summary: ID による製品取得
      tags:
      - basic
  /product-test/{id}:
    get:
      description: 製品を 1 件返す
      operationId: getProductTestById
      parameters:
      - description: product id
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              example:
                id: 1
                name: 製品 A
                is_limited: false
                released_at: 2021/09/01
              schema:
                $ref: '#/components/schemas/product-test'
          description: 成功時
      summary: ID による製品取得
      tags:
      - basic
components:
  schemas:
    product:
      allOf:
      - $ref: '#/components/schemas/product_allOf'
      - $ref: '#/components/schemas/entity-base'
    product-test:
      allOf:
      - $ref: '#/components/schemas/product_test_allOf'
      - $ref: '#/components/schemas/entity-base'
    entity-base:
      description: 共通プロパティ
      properties:
        created_at:
          description: 生成日時
          example: 1999-07-07T00:00:00+09:00
          format: date-time
          type: string
        updated_at:
          description: 更新日時
          example: 1999-07-07T00:00:00+09:00
          format: date-time
          type: string
        deleted_at:
          description: 削除日時
          example: 1999-07-07T00:00:00+09:00
          format: date-time
          type: string
      type: object
    product_allOf:
      description: 製品
      properties:
        id:
          description: 製品の ID
          example: 1
          type: integer
        name:
          description: 製品名
          example: 製品 A
          type: string
        is_limited:
          description: 限定販売かどうか
          example: false
          type: boolean
        released_at:
          description: 発売日
          example: 2021/09/01
          type: string
      required:
      - id
      type: object
    product_test_allOf:
      description: テスト製品
      properties:
        id:
          description: テスト製品の ID
          example: 1
          type: integer
        name:
          description: 製品名
          example: 製品 A
          type: string
        type:
          description: タイプ
          example: タイプ A
          type: string
        is_limited:
          description: 限定販売かどうか
          example: false
          type: boolean
        released_at:
          description: 発売日
          example: 2021/09/01
          type: string
      required:
      - id
      - name
      type: object
