type: object
description: テスト製品
properties:
  id:
    type: integer
    description: テスト製品の ID
    example: 1
  name:
    type: string
    description: 製品名
    example: 製品 A
  type:
    type: string
    description: タイプ
    example: タイプ A
  is_limited:
    type: boolean
    description: 限定販売かどうか
    example: false
  released_at:
    type: string
    description: 発売日
    example: 2021/09/01
required:
  - id
  - name
